# Generated by Django 4.2.29 on 2026-04-19 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='stock',
            name='symbol',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
