# Generated by Django 4.2.29 on 2026-04-19 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_alter_stock_price_alter_stock_symbol_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='stock',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
