# Generated by Django 4.2.29 on 2026-04-22 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0003_remove_stock_timestamp_stock_last_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
