# Generated by Django 4.2.29 on 2026-04-23 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0005_stockhistory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockhistory',
            old_name='price',
            new_name='close',
        ),
        migrations.AddField(
            model_name='stockhistory',
            name='high',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stockhistory',
            name='low',
            field=models.FloatField(default=0.1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stockhistory',
            name='open',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
