# Generated by Django 4.2.29 on 2026-04-23 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0006_rename_price_stockhistory_close_stockhistory_high_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockhistory',
            name='close',
        ),
        migrations.RemoveField(
            model_name='stockhistory',
            name='high',
        ),
        migrations.RemoveField(
            model_name='stockhistory',
            name='low',
        ),
        migrations.RemoveField(
            model_name='stockhistory',
            name='open',
        ),
        migrations.AddField(
            model_name='stockhistory',
            name='price',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
